version: '3.8'

services:
  bardak:
    build: .
    ports:
      - "8085:8085"
    volumes:
      - ./things:/app/things:rw
      - ./trash:/app/trash:rw
    read_only: true
    tmpfs:
      - /tmp
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

